### ISSUE TITLE
get_dataframe() crashes if 'id' is not included in ModelSerializer fields

### ISSUE THREAD

**Issue by sheppard** [wq/django-rest-pandas#13]
See http://paste.ubuntu.com/10862242/.

Currently the only way to get around this (short of adding `id` back to the included fields) is to subclass `PandasSerializer` and override [get_index()](https://github.com/wq/django-rest-pandas/blob/v0.3.2/rest_pandas/serializers.py#L22-L26) to ensure it returns `None` (or any included field).

A better solution would be to have the default `get_index()` check for the `id` field before using it as the index, or to make it return `None` by default and always require it to be overridden for users that want an index to be set on their `DataFrame`.

**Comment by jsmedmar** [comment]
I like sheppard solution, another option would be to check for `pk` as well.
