### ISSUE TITLE
Excel file generation Exception Response Data is not a Dataframe.

### ISSUE THREAD

**Issue by klahnen** [wq/django-rest-pandas#18]
Basically I am trying to generate XLSX File and stream it for download.

My tests are like this:

    response = self.client.get('/grades/export?format=csv')
    print response
    self.assertEqual(response.status_code, status.HTTP_200_OK)
    print '===================================================='
    response = self.client.get('/grades/export?format=xlsx')
    print response
    self.assertEqual(response.status_code, status.HTTP_200_OK)

And my Output is this:

    ERROR: test_export_grades_to_excel (functional_tests.tests.GradesExportTestCase)
    Traceback (most recent call last):
    File "C:\Users\lhernandezm\Documents\Git\alvin\functional_tests\tests.py", line 528, in test_export_grades_to_excel
    response = self.client.get('/grades/export?format=xlsx')
    File "C:\Users\path\lib\site-packages\rest_framework\test.py", line 162, in get
    response = super(APIClient, self).get(path, data=data, **extra)
    File "C:\Users\path\lib\site-packages\rest_framework\test.py", line 88, in get
    return self.generic('GET', path, **r)
    File "C:\Users\path\lib\site-packages\django\test\client.py", line 379, in generic
    return self.request(**r)
    File "C:\Users\path\lib\site-packages\rest_framework\test.py", line 159, in request
    return super(APIClient, self).request(**kwargs)
    File "C:\Users\path\lib\site-packages\rest_framework\test.py", line 111, in request
    request = super(APIRequestFactory, self).request(**kwargs)
    File "C:\Users\path\lib\site-packages\django\test\client.py", line 466, in request
    six.reraise(*exc_info)
    File "C:\Users\path\lib\site-packages\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
    File "C:\Users\path\lib\site-packages\django\template\response.py", line 158, in render
    self.content = self.rendered_content
    File "C:\Users\path\lib\site-packages\rest_framework\response.py", line 71, in rendered_content
    ret = renderer.render(self.data, media_type, context)
    File "C:\Users\path\lib\site-packages\rest_pandas\renderers.py", line 30, in render
    "Response data is a %s, not a DataFrame!" % type(data)
    Exception: Response data is a <type 'NoneType'>, not a DataFrame!

CSV Test Succeeds! But XLSX gives me the error above.

My current ``pip freeze`` is:
    colorama==0.3.3
    coverage==3.7.1
    decorator==4.0.4
    diff-match-patch==20121119
    Django==1.8.2
    django-appconf==1.0.1
    django-audit-log==0.8.0
    django-autoslug==1.8.0
    django-cities-light==3.1.2
    django-compressor==1.5
    django-cors-headers==1.1.0
    django-email-as-username==1.6.7
    django-extensions==1.5.5
    django-filter==0.10.0
    django-guardian==1.3
    django-import-export==0.2.8
    django-rest-swagger==0.3.4
    djangorestframework==3.2.4
    djangorestframework-jwt==1.7.2
    factory-boy==2.5.2
    fake-factory==0.5.2
    flake8==2.4.1
    ipdb==0.8.1
    ipython==4.0.0
    ipython-genutils==0.1.0
    jdcal==1.0
    Markdown==2.6.2
    mccabe==0.3.1
    numpy==1.10.0
    openpyxl==1.8.6
    pandas==0.16.2
    path.py==8.1.1
    pep8==1.5.7
    pickleshare==0.5
    Pillow==2.8.1
    psycopg2==2.6.1
    pyflakes==0.8.1
    Pygments==2.0.2
    PyJWT==1.3.0
    python-dateutil==2.4.2
    pytz==2015.6
    PyYAML==3.11
    rest-pandas==0.3.2
    selenium==2.47.1
    simplegeneric==0.8.1
    six==1.9.0
    tablib==0.10.0
    traitlets==4.0.0
    Unidecode==0.4.18
    Unipath==1.1
    Werkzeug==0.10.4
    wheel==0.24.0
    XlsxWriter==0.7.6
    xlwt==1.0.0

I know this is beta so Docs are for next development phase, please let me know if I am doing something wrong or if it is a bug.

Also I would like to collaborate with Docs.

**Comment by klahnen** [comment]
Hi,

I solve this, with this code:
def transform_dataframe(self, dataframe):
        format = self.request.query_params.get('format', None)

        if format == 'xlsx':
            from pandas.io.excel import ExcelWriter
            writer = ExcelWriter('output.xlsx')
            dataframe.to_excel(writer, 'Page1')
            return dataframe
        elif format == 'csv':
            return dataframe

As the error says we need to return dataframe and nothing else.

So this works con Mac OS Yosemite, but on Windows 7 I got:

        WindowsError: [error 32] The process cannot access the file because it is being used by another process.

**Comment by sheppard** [comment]
Yes, the documentation definitely needs a lot more detail.  Eventually I may move to separate doc pages, but for now feel free to suggest improvements to README.md I will be sure to incorporate them.

(see #19)
