### ISSUE TITLE
PandasView Upload File - Example Request

### ISSUE THREAD

**Issue by klahnen** [wq/django-rest-pandas#20]
Hi,

Currently I am working on receiving files form users (csv, xlsx) and pass this files to rest-pandas so its content can be imported to your models or any custom python object.

Before going further I would like to know if the scope of this project includes importing data from files.

If this is part of scope or if project leaders agree to include this part I will be posting my progress.

Have a nice day!

**Comment by sheppard** [comment]
File import has not been a focus of DRP so far, but it certainly could be added.  To do this the DRP way, you could do something like this:

1. Create [`Parser`](http://www.django-rest-framework.org/api-guide/parsers/) classes for each supported format.  These would directly correspond to the existing `Renderer` classes but work the other way.  The `parse()` method on each class would accept the request data and return a `DataFrame` via e.g. `DataFrame.read_excel()`.

2. Extend the existing `PandasSerializer` so it can handle incoming DataFrames as returned by the parsers.  The main goal would be to convert the serializer into a `list` of `dict`s for further processing by the built-in Django REST Framework serializer.  Something like this might work (I haven't tested it):

    ```python
    class PandasSerializer(BaseSerializer):
        def to_internal_value(self, dataframe):
            data = dataframe.to_dict('records')
            return super(PandasSerializer).to_internal_value(data)
```

3. Once these pieces are in place, Django REST Framework should be able to handle validating data types and inserting records in the database - so you shouldn't need to write any of that code yourself.  You would likely want to extend `ListCreateAPIView` to enable create access, and it's possible you may need to leverage [Django REST Framework Bulk](https://github.com/miki725/django-rest-framework-bulk) for bulk record creation.

As you are likely aware, there are [a number of existing solutions](https://www.djangopackages.com/search/?q=import) for importing spreadsheet data into Django, so be sure to take a look at those to see if any meet your needs.  To my knowledge, none are integrated with Django REST Framework in the way that DRP is.  I also have my own work-in-progress solution ([here](https://github.com/wq/django-data-wizard)), though it's not quite ready for general purpose use and it also doesn't use Pandas.

**Comment by klahnen** [comment]
Thanks for your response, I will walk through the steps you wrote. If I get it work, be sure I will do corresponding pull request. Have a nice day!

**Comment by klahnen** [comment]
Hi, Sheppard,

Can you help me with a quick check to see if this code corres corresponds with step 1. ?

Thanks in advance for your time, in 2015 I started with Django, DRF and DRF-Pandas so my exprience is short.

    import pandas
    import csv
    from rest_framework.parsers import BaseParser
    from rest_pandas.renderers import PandasCSVRenderer


    class CSVParser(BaseParser):
        """
        Parses CSV-dataframe data.
        """
        media_type = 'text/csv'
        renderer_class = PandasCSVRenderer

        def parse(self, stream, media_type=None, parser_context=None):
            """
            Parses the incoming bytestream as CSV and returns the resulting data.
            """
            parser_context = parser_context or {}

            try:
                dia = csv.excel()
                data = stream.read().decode(encoding)
                return pandas.read_csv(data, dialect=dia)
            except ValueError as exc:
                raise ParseError('CSV parse error - %s', parser_context=None)

**Comment by klahnen** [comment]
This is my candidate view:

    class CSVUploadView(CreateAPIView):
        serializer_class = GradesImportSerializer
        permission_classes = (IsAuthenticated,)
        parser_classes = (CSVParser,)

And my candidate serializer:

    class CSVImportSerializer(PandasSerializer):

        def to_internal_value(self, dataframe):
            data = dataframe.to_dict('records')
            return super(PandasSerializer).to_internal_value(data)


And my tests are failing with this error message, I guess is something with serializer above.
I am posting here, because I already googled this, I did'nt find any clues for solving this

Error stack:

    File "/home/vagrant/django_project/functional_tests/grades/tests.py", line 272, in test_import_grades_from_csv
        response = self.client.post('/grades/import/', data, format="multipart")
      File "/home/vagrant/.virtualenvs/django_project/local/lib/python2.7/site-packages/rest_framework/test.py", line 170, in post
        path, data=data, format=format, content_type=content_type, **extra)
      File "/home/vagrant/.virtualenvs/django_project/local/lib/python2.7/site-packages/rest_framework/test.py", line 92, in post
        return self.generic('POST', path, data, content_type, **extra)
      File "/home/vagrant/.virtualenvs/django_project/local/lib/python2.7/site-packages/django/test/client.py", line 379, in generic
        return self.request(**r)
      File "/home/vagrant/.virtualenvs/django_project/local/lib/python2.7/site-packages/rest_framework/test.py", line 159, in request
        return super(APIClient, self).request(**kwargs)
      File "/home/vagrant/.virtualenvs/django_project/local/lib/python2.7/site-packages/rest_framework/test.py", line 111, in request
        request = super(APIRequestFactory, self).request(**kwargs)
      File "/home/vagrant/.virtualenvs/django_project/local/lib/python2.7/site-packages/django/test/client.py", line 466, in request
        six.reraise(*exc_info)
      File "/home/vagrant/.virtualenvs/django_project/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/home/vagrant/.virtualenvs/django_project/local/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
        return func(*args, **kwargs)
      File "/home/vagrant/.virtualenvs/django_project/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
        return view_func(*args, **kwargs)
      File "/home/vagrant/.virtualenvs/django_project/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
        return self.dispatch(request, *args, **kwargs)
      File "/home/vagrant/.virtualenvs/django_project/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
        response = self.handle_exception(exc)
      File "/home/vagrant/.virtualenvs/django_project/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
        response = handler(request, *args, **kwargs)
      File "/home/vagrant/.virtualenvs/django_project/local/lib/python2.7/site-packages/rest_framework/generics.py", line 192, in post
        return self.create(request, *args, **kwargs)
      File "/home/vagrant/.virtualenvs/django_project/local/lib/python2.7/site-packages/rest_framework/mixins.py", line 19, in create
        serializer = self.get_serializer(data=request.data)
      File "/home/vagrant/.virtualenvs/django_project/local/lib/python2.7/site-packages/rest_framework/generics.py", line 111, in get_serializer
        return serializer_class(*args, **kwargs)
      File "/home/vagrant/.virtualenvs/django_project/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 516, in __init__
        assert self.child is not None, '`child` is a required argument.'
    AssertionError: `child` is a required argument.

**Comment by klahnen** [comment]
Hi,

I realized my problem is with CSVParser, by now the code of CSVParser is:


    class CSVParser(FileUploadParser):
        media_type = "text/csv"
        renderer_class = PandasCSVRenderer

        def parse(self, stream, media_type=None, parser_context=None):
            parser_context = parser_context or {}
            encoding = parser_context.get('encoding', settings.DEFAULT_CHARSET)
            request = parser_context['request']
            import ipdb; ipdb.set_trace()
            file_obj = request.data['file'] # Point of Failure
            dia = csv.excel()
            return pandas.read_csv(file_obj, dialect=dia)

Current error: `MultiValueDictKeyError: "'file'"`

**Comment by sheppard** [comment]
Your first approach (reading directly from the stream) looked like it was the right approach for processing a file posted via ajax with a media type of "text/csv".  `request.data` is for parsing a `multipart/form-data` which where you might file as one of several fields.

In your first example, the error in the serializer was likely because it is a [ListSerializer](http://www.django-rest-framework.org/api-guide/serializers/#listserializer) class and couldn't find the child `Serializer`.  Rather than assigning a `PandasSerializer` to your view directly as `serializer_class`, you can create a regular serializer and set `list_serializer_class` on its `Meta`:

```python
class GradesImportSerializer(ModelSerializer):
    class Meta:
        list_serializer_class = CSVImportSerializer
        model = GradesModel # or whatever
```

The view would be the same:
```
class CSVUploadView(CreateAPIView):
    serializer_class = GradesImportSerializer
    permission_classes = (IsAuthenticated,)
    parser_classes = (CSVParser,)
```

**Comment by klahnen** [comment]
Hi,

I make the adjustments you said, and I got the following error on my test,
Can you help me with a clue to figure out where I need to fix something?


```bash
Traceback (most recent call last):
  File "/home/vagrant/alvin/functional_tests/grades/tests.py", line 275, in test_import_grades_from_csv
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201
```

My I tried this test:


```python
def _create_test_file(self, path):
        f = open(path, 'w')
        content = '\n'.join(
                            ("id, student, value, status, string_value",
                             "1, alvin, 5.0, G, stringvalue"))
        f.write(content)
        f.close()        
        return path

def test_import_grades_from_csv(self):
    self.assertEqual(0, Grade.objects.count())
    response = self.client.post('/api-token-auth/',
                                    {
                                        "username": "user",
                                        "password": "pass"
                                    }, format='json')

    token = response.data['token']
    self.client.credentials(HTTP_AUTHORIZATION='JWT '+token)

    data = self._create_test_file('/tmp/test_upload')

    response = self.client.post('/grades/import', data, content_type="text/csv")
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
```
My CSVParser is:

```python
class CSVParser(BaseParser):
    """
    Parses CSV-dataframe data.
    """
    media_type = 'text/csv'
    renderer_class = PandasCSVRenderer

    def parse(self, stream, media_type=None, parser_context=None):
        """
        Parses the incoming bytestream as CSV and returns the resulting data.
        """
        parser_context = parser_context or {}
        encoding = parser_context.get('encoding', settings.DEFAULT_CHARSET)

        try:
            dia = csv.excel()
            data = stream.read()
            df = pandas.read_csv(data, dialect=dia)
            print df
            return df
        except ValueError as exc:
            raise ParseError('CSV parse error - %s', parser_context=None)
```

And `df` printed is:

```
   id  student   value  status  string_value
0   1    alvin       5       G   stringvalue
```

My Serializers are:

```python
class CSVImportSerializer(PandasSerializer):

    def to_internal_value(self, dataframe):
        data = dataframe.to_dict('records')
        return super(PandasSerializer).to_internal_value(data)


class GradesImportSerializer(serializers.ModelSerializer):
    class Meta:
        list_serializer_class = CSVImportSerializer
        model = Grade
```

**Comment by sheppard** [comment]
Getting closer!  Can you verify that the `GradesImportSerializer` is being initialized with `many=True`?  It is probably being initialized with `many=False` which is what `CreateAPIView` will do by default.  You might need to override the `create()` function - see Django REST Framework bulk's [BulkCreateModelMixin](https://github.com/miki725/django-rest-framework-bulk/blob/master/rest_framework_bulk/drf3/mixins.py#L32) as an example.  The main difference is that you'll be checking to see if `request.data` is an instance of a `DataFrame` rather than a `list`.

**Comment by klahnen** [comment]
Yes! we are closer. I apply your recommendations and my code basically looks like this:

```python
class GradesImportView(CreateAPIView):
    serializer_class = GradesImportSerializer
    permission_classes = (IsAuthenticated,)
    parser_classes = (CSVParser,)

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data, many=True)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        return Response(serializer.data, status=status.HTTP_201_CREATED)

class CSVImportSerializer(BaseSerializer):

    def to_internal_value(self, dataframe):
        data = dataframe.to_dict('records')
        return super(PandasSerializer).to_internal_value(data)


class GradesImportSerializer(serializers.ModelSerializer):

    class Meta:
        # list_serializer_class = CSVImportSerializer
        model = Grade
        fields = (
            'id',
            'student',
            'value',
            'string_value'
            )

```

I needed to comment `list_serializer_class` because my test was throwing this `super(BaseSerializer, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'child'` But if this line commented `CSVImportSerializer` loose sense.

After that my test now is saying:
```html
Vary: Accept, Cookie
X-Frame-Options: SAMEORIGIN
Content-Type: application/json
Allow: POST, OPTIONS

{"non_field_errors":["Expected a list of items but got type \"DataFrame\"."]}
```

To be honest I am not understanding whats going on, something tells me that `CSVParser` should handle that.

```python
class CSVParser(BaseParser):
    """
    Parses CSV-dataframe data.
    """
    media_type = 'text/csv'
    renderer_class = PandasCSVRenderer

    def parse(self, stream, media_type=None, parser_context=None):
        """
        Parses the incoming bytestream as CSV and returns the resulting data.
        """
        parser_context = parser_context or {}
        encoding = parser_context.get('encoding', settings.DEFAULT_CHARSET)

        try:
            dia = csv.excel()
            data = stream.read()
            df = pandas.read_csv(data, dialect=dia)
            return df
        except ValueError as exc:
            raise ParseError('CSV parse error - %s', parser_context=None)
```

**Comment by klahnen** [comment]
I ran `ipdb` in my view and I got this:

```python
ipdb> n
> /home/vagrant/django/grades/views.py(178)create()
    177         serializer = self.get_serializer(data=request.data, many=True)
--> 178         serializer.is_valid(raise_exception=True)
    179         self.perform_create(serializer)

ipdb> serializer
GradesImportSerializer(context={u'view': <grades.views.GradesImportView object>, u'request': <rest_framework.request.Request object>, u'format': None}, data=  student   value  status  string_value
0   alvin       5       G   stringvalue
1   alvin       9       G   stringvalue, many=True):
    id = IntegerField(label='ID', read_only=True)
    student = PrimaryKeyRelatedField(allow_null=True, queryset=User.objects.all(), required=False)
    value = DecimalField(decimal_places=4, max_digits=18)
    string_value = CharField(allow_blank=True, max_length=10, required=False)
ipdb>
```
As you can see serializer is getting dataframe instead of dict, I guess this is because I commented `list_serializer_class`

**Comment by klahnen** [comment]
Hi sheppard,

It is solved.

My final view is:
```python
class GradesImportView(CreateAPIView):
    serializer_class = GradesImportSerializer
    permission_classes = (IsAuthenticated,)
    parser_classes = (CSVParser,)

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data, many=True)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        return Response(serializer.data, status=status.HTTP_201_CREATED)

```

My final serializers are:
```python
class CSVImportSerializer(serializers.ListSerializer):

    def to_internal_value(self, dataframe):
        data = dataframe.to_dict('records')
        return super(CSVImportSerializer, self).to_internal_value(data)


class GradesImportSerializer(serializers.ModelSerializer):
    student = serializers.SlugRelatedField(read_only=True, slug_field='username')

    class Meta:
        list_serializer_class = CSVImportSerializer
        model = Grade
        fields = (
            'student',
            'value',
            'string_value'
            )
```

My passing test was:
```python
class GradesImportTestCase(APITestCase):

    def setUp(self):
        self.user = UserFactory(username='user', password='pass')

    def _create_test_file(self, path):
        f = open(path, 'w')
        content = '\n'.join(
                            ("student,value,status,string_value",
                             "alvin,5.0,G,s_val",
                             "alvin,9.0,G,s_val"))
        f.write(content)
        f.close()
        return path

    def test_import_grades_from_csv(self):
        self.assertEqual(0, Grade.objects.count())
        response = self.client.post('/api-token-auth/',
                                        {
                                            "username": "user",
                                            "password": "pass"
                                        }, format='json')

        token = response.data['token']
        self.client.credentials(HTTP_AUTHORIZATION='JWT '+token)

        data = self._create_test_file(r'/tmp/test_upload.csv')

        response = self.client.post('/grades/import', data, content_type="text/csv")
        # print response
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(2, Grade.objects.count())
```

Thanks so much for your coaching and I hope this can contribute positively to `django-rest-pandas`

**Comment by sheppard** [comment]
Great, glad you got it working.  Feel free to put together a pull request and we can start working on incorporating this into DRP.
