### ISSUE TITLE
Change Json format ?

### ISSUE THREAD

**Issue by slamer59** [wq/django-rest-pandas#26]
Hello,
I need to construct my json like :
```
{
  "x": [
    5.0,
    3.0,
    8.0,
    5.0]
  ], 
  "y": [
    7.0,
    2.0,
    6.0,
    4.0]
}
```

I have this, which is exactly what to_json gives:
`[{"x":5,"y":7},{"x":3,"y":2},{"x":8,"y":6},{"x":5,"y":4}]`

Is it possible to change this behavior ?
It might be a pandas question.

Thanks for your efforts ! I understand better how REST works now :)
Thomas

**Comment by sheppard** [comment]
You can change the orientation using the `orient` URL parameter which is passed on to `DataFrame.to_json()`.   I don't know if there is an `orient` that does exactly what you want but `columns` or `values` might do the trick.

**Comment by slamer59** [comment]
Hello,
I find a solution for this !
data_frame = pd.DataFrame.from_dict(data, orient='index')

I have to play with orientation of data as you suggested. Going from 'index' to 'columns' do the trick.

Thanks for your suggestion and this app. It helps me a lot to understand django rest :)
