### ISSUE TITLE
Datetimefield is serialized to str

### ISSUE THREAD

**Issue by martinwk** [wq/django-rest-pandas#27]
When I serialize this model

```class Well(models.Model):
    site            = models.ForeignKey(Site, on_delete=models.CASCADE)
    name         = models.CharField(max_length=100, )
    start_date_time = models.DateTimeField(auto_now=False, auto_now_add=False, verbose_name='Date and time at which the well is deployed.')
```

with this serializer
```
class FileSerializer(serializers.ModelSerializer):
    class Meta:
        model = Well
        fields = ('id', 'name', 'site', )
```
The resulting dataframe has a column `start_date_time` but this is a string rather than a datetime object. I work around this by using `transform_dataframe` and convert the column using `pandas.to_datetime` function. Is this the way to go or am I missing someting?

**Comment by sheppard** [comment]
You can turn off the string serialization by adding the following to your serializer:

```python
class FileSerializer(serializers.ModelSerializer):
    start_date_time = serializers.DateTimeField(format=None)
```

I updated the README with more information.
