### ISSUE TITLE
Set filename in view

### ISSUE THREAD

**Issue by chicocvenancio** [wq/django-rest-pandas#31]
Thanks for this great software, I have been using PandasSimpleView to greatly simplify the rest api and provide different useful formats.

One feature that seems missing to me is the ability to suggest a filename for the browser, currently the views do not set a name and it will be confusing for my user to download several tables of data with the same "download.format" name.

I think ~it is currently possible to override the renderer and set this, but~ it would be a nice feature to have as a default option in the view.

**Comment by sheppard** [comment]
Thanks for the suggestion.  This is available in [v1.1.0](https://github.com/wq/django-rest-pandas/releases/tag/v1.1.0).
