### ISSUE TITLE
date_format not used when creating csv

### ISSUE THREAD

**Issue by martinwk** [wq/django-rest-pandas#37]
To modify the behavior of the csv renderer, I have subclassed `PandasCSVRenderer`

```
class PandasCSVNoColNoIndexRenderer(PandasCSVRenderer):
    def get_pandas_kwargs(self, data, renderer_context):
        output = super().get_pandas_kwargs(data, renderer_context)
        output['header'] = False
        output['index'] = False
        # Remark on padding zeros: 
        #   removing padding zeros is platform dependent so we better leave it this way (%-d in linux, %#d in windos)
        #   https://stackoverflow.com/questions/28894172/why-does-d-or-e-remove-the-leading-space-or-zero
        output['sep'] = ';'
        output['date_format'] = '%d-%m-%Y %H:%M'  

        return output
```
All options work out fine, except for the 'date_format' option. I have set in settings.py
```

```

and indeed when inside get_pandas_kwargs
```
renderer_context['response'].data.iloc[10,3]
```
returns 
```
Timestamp('1985-07-01 00:00:00')
```
The string is also correct as 
```
renderer_context['response'].data.iloc[10,3].strftime('%d-%m-%Y %H:%M')
```
yields the desired output (30-11-1999 01:02)

Do you have any clue why this is happening?

**Comment by sheppard** [comment]
I added a simple test for this and it works, so I was unable to reproduce the issue.  I don't see any obvious problems in your example.  Maybe the view is selecting the wrong renderer?

**Comment by martinwk** [comment]
Sorry to get back this late to you, but I recently accidently came to what seems to be the cause. The dataframe that needs to be rendered did not have `datetime` columns but `object` columns because its datetypes were both strings and datetimes (this was by my design). It seems this prevents the datetime objects in the dataframe to be rendered correctly. I think this is a pandas thing with the `to_csv` method. It works fine with the `to_excel` method though...
