### ISSUE TITLE
GeoPandas support

### ISSUE THREAD

**Issue by sheppard** [wq/django-rest-pandas#5]
Add a renderer or two that leverage GeoPandas exports.  At a minimum, support GeoJSON and Shapefiles (perhaps as a .zip?).

**Comment by auvipy** [comment]
you could have some ideas from django rest framework GIS extension

**Comment by sheppard** [comment]
Yes, the GeoJSON renderer would overlap with functionality in DRF-GIS, much like DRP's JSON renderer overlaps with DRF's built-in JSON renderer.  The main advantage to using DRP+GeoPandas versus DRF-GIS would be the ability to use pandas to transform or summarize the data before rendering it.
